apiVersion: v2
name: paperless-ngx
description: "A community-supported supercharged version of paperless: scan, index and archive all your physical documents"
home: https://charts.gabe565.com/charts/paperless-ngx/
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/b948750/src-ui/src/assets/logo-notext.svg
type: application
version: 0.25.0
# renovate datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.14.7
kubeVersion: ">=1.22.0-0"
keywords:
  - documents
  - ocr
  - paper
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1
  - name: postgres
    version: 0.12.0
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: mariadb
    version: 0.6.1
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
  - name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.14.1
    condition: redis.enabled
sources:
  - https://github.com/paperless-ngx/paperless-ngx
annotations:
  artifacthub.io/alternativeName: paperless
  artifacthub.io/changes: |-
    - kind: fixed
      description: Allow for custom db secrets name
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/paperless-ngx/paperless-ngx
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/paperless-ngx
